import CreativeLab from '../components/CreativeLab'
import StudioInteractions from '../components/StudioInteractions'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import BrandLogo from '../components/BrandLogo'
import FeatureShowcase from '../components/FeatureShowcase'
import Icon from '../components/Icon'
import PricingSelector from '../components/PricingSelector'
import '../landing-studio.css'

const FAQ=[
 ['Apakah konten langsung terbit ke media sosial?','Belum. plannersm.co membantu perencanaan, produksi, dan persetujuan konten. Publikasi tetap dilakukan melalui aplikasi media sosial masing-masing.'],
 ['Paket dihitung per akun sosial atau per workspace?','Harga berlaku untuk satu workspace. Satu workspace digunakan untuk mengelola rencana konten satu brand bersama tim. Jika menangani beberapa brand, kamu dapat membuat workspace terpisah dan memilih paket untuk masing-masing.'],
 ['Apa perbedaan paket Gratis, Studio, dan Pro?','Ketiganya menyediakan fitur dasar perencanaan konten. Studio dan Pro menawarkan kapasitas penyimpanan lebih besar untuk operasional tim. Rincian paket dan harga terbaru tersedia pada bagian Paket & harga.'],
 ['Bagaimana cara membeli paket dan add-on?','Pilih paket, periode, dan add-on yang diperlukan. Bayar melalui QRIS, lalu unggah bukti pembayaran. Paket aktif setelah admin memeriksa dan menyetujui pembayaran. Tidak ada pendebitan otomatis.'],
 ['Apa yang terjadi saat add-on penyimpanan berakhir?','Kapasitas kembali mengikuti paket dan add-on lain yang masih aktif. File tidak dihapus otomatis. Jika pemakaian melebihi kapasitas, kurangi materi yang tidak diperlukan atau perpanjang add-on sebelum mengunggah file berikutnya.'],
 ['Apakah tersedia AI caption dan analitik otomatis?','Saat ini belum tersedia AI pembuat caption maupun pengambilan angka engagement otomatis. Fitur yang tersedia berfokus pada pengelolaan rencana, materi, tugas, dan persetujuan konten.']
]
export default function Landing(){
 const [menu,setMenu]=useState(false)
 const [scrolled,setScrolled]=useState(false)
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>48);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[])
 useEffect(()=>{const previous=document.title;document.title='plannersm | Ruang gerak tim kreatif';return()=>{document.title=previous}},[])
 useEffect(()=>{if(!menu)return;const close=e=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[menu])
 return <div className="studio-landing hero-overlay-page">
 <a className="studio-skip" href="#isi">Lewati navigasi</a>
 <header className={`studio-nav${scrolled ? ' is-scrolled' : ''}${menu ? ' menu-open' : ''}`}><Link className="studio-logo" to="/"><BrandLogo/></Link><nav aria-label="Navigasi landing page" className={menu?'is-open':''}><a href="#fitur" onClick={()=>setMenu(false)}>Fitur</a><a href="#cara-kerja" onClick={()=>setMenu(false)}>Cara kerja</a><a href="#paket" onClick={()=>setMenu(false)}>Paket & harga</a><a href="#pertanyaan" onClick={()=>setMenu(false)}>Pertanyaan</a></nav><div className="studio-nav-actions"><Link to="/login">Masuk</Link><Link to="/signup" className="studio-button">Mulai gratis</Link></div><button className="studio-menu" type="button" onClick={()=>setMenu(!menu)} aria-label={menu?'Tutup menu':'Buka menu'} aria-expanded={menu}><Icon name={menu?'close-outline':'menu-outline'} size={25}/></button></header>
 <main id="isi">
 <section className="studio-hero"><div className="studio-hero-copy"><p className="studio-category">Untuk brand, kreator, dan tim kamu</p><h1><span className="hero-desktop-copy">Ide boleh ke mana saja.<br/>Kerjanya tetap tertata.</span><span className="hero-mobile-copy">Ide besar.<br/>Kerja lebih tertata.</span></h1><p className="studio-lead"><span className="hero-desktop-copy">Dari ide pertama sampai klien bilang oke. Susun konten, bagi tugas, dan review bareng di plannersm.</span><span className="hero-mobile-copy">Susun konten dan review bareng tim, di satu tempat.</span></p><div className="studio-hero-actions"><Link className="studio-button studio-button-large" to="/signup"><span className="hero-desktop-copy">Mulai susun konten</span><span className="hero-mobile-copy">Mulai gratis</span></Link><a className="studio-secondary" href="#cara-kerja">Kenali fiturnya <Icon name="play-circle-outline" size={21}/></a></div><p className="studio-small">Tersedia paket Gratis. Tanpa kartu kredit.</p></div>
 <figure className="studio-hero-scene"><picture><source media="(max-width: 700px)" srcSet="/images/studio-mobile-lavender.png"/><img src="/images/studio-team-hero.png" alt="Ilustrasi 3D tim kreatif merencanakan konten bersama di studio" width="1860" height="846" fetchpriority="high"/></picture></figure>
 </section>

 <section className="studio-section" id="fitur"><div className="studio-section-heading"><h2>Lebih banyak berkarya.<br/>Lebih sedikit bolak-balik.</h2><p>Pilih fitur dan lihat bagaimana tim kamu bisa memakainya.</p></div><FeatureShowcase/></section>
 <CreativeLab/>
 <section className="studio-review"><div className="studio-review-image"><img src="/images/studio-review.png" alt="Ilustrasi dua anggota tim meninjau rencana visual konten" width="1448" height="1086" loading="lazy"/></div><div className="studio-review-copy"><span className="studio-section-kicker">Review dan persetujuan</span><h2>Kirim ke klien.<br/>Lanjut dari feedback.</h2><p>Bagikan satu link review. Catatan dan persetujuan tetap bersama kontennya, jadi tim tahu apa yang perlu dilanjutkan.</p><ul><li><Icon name="checkmark-circle-outline"/>Klien meninjau tanpa membuat akun</li><li><Icon name="checkmark-circle-outline"/>Catatan revisi tersimpan bersama konten</li><li><Icon name="checkmark-circle-outline"/>Brand dan materi terpisah per workspace</li></ul><a href="#paket" className="studio-text-link">Lihat pilihan paket <Icon name="arrow-forward-outline"/></a></div></section>
 <section className="studio-section studio-process" id="cara-kerja"><div className="studio-section-heading"><h2>Satu tim.<br/>Tahu langkah berikutnya.</h2><p>Siapa mengerjakan apa, semuanya terlihat.</p></div><div className="studio-process-layout"><ol><li><b>1</b><div><h3>Susun agenda konten</h3><p>Tentukan tema, tanggal, dan platform untuk setiap konten.</p></div></li><li><b>2</b><div><h3>Bagikan pekerjaan</h3><p>Lengkapi brief dan materi, lalu tetapkan anggota tim yang mengerjakan.</p></div></li><li><b>3</b><div><h3>Tinjau sebelum tayang</h3><p>Periksa progres, kumpulkan persetujuan, dan siapkan materi final.</p></div></li></ol><div className="studio-board" aria-label="Contoh alur kerja konten"><div className="studio-board-top"><strong>Agenda konten</strong><span>Contoh workspace</span></div><div className="studio-board-columns">{[['Dalam produksi','Katalog produk baru','Foto produk · Instagram','Perbarui visual dan caption.'],['Menunggu review','Tips memilih produk','Carousel · Instagram','Materi siap ditinjau klien.'],['Siap tayang','Cerita pelanggan','Video · TikTok','Persetujuan sudah diterima.']].map(([status,title,kind,note],i)=><div key={status}><span className={'studio-board-status status-'+i}>{status}</span><article><div className={'studio-board-visual visual-'+i}><Icon name={['images-outline','albums-outline','videocam-outline'][i]} size={32}/></div><h4>{title}</h4><small>{kind}</small><p>{note}</p><span className="studio-board-person">{['DI','RA','AN'][i]}<span>Penanggung jawab</span></span></article></div>)}</div></div></div></section>
 <section className="studio-pricing-section" id="paket"><div className="studio-section-heading"><h2>Ruang untuk ide kamu.<br/>Paket sesuai kebutuhan.</h2><p>Mulai gratis. Tambah kapasitas saat tim kamu membutuhkannya.</p></div><PricingSelector/></section>
 <section className="studio-section studio-faq-section" id="pertanyaan"><div><h2>Masih penasaran?</h2><p>Butuh bantuan memilih paket untuk tim?</p><a href="https://wa.me/6285111037992" target="_blank" rel="noopener noreferrer" className="studio-text-link">Bicara dengan admin <Icon name="logo-whatsapp"/></a></div><div className="studio-faq">{FAQ.map(([q,a])=><details key={q}><summary>{q}<Icon name="add-outline" size={20}/></summary><p>{a}</p></details>)}</div></section>
 <section className="studio-final"><div><h2>Konten berikutnya?<br/>Yuk, kerjakan bareng.</h2><p>Buka ruang kerja untuk ide dan tim kamu.</p></div><Link to="/signup" className="studio-button studio-button-light">Mulai gratis</Link></section>
 </main>
 <footer className="studio-footer"><div><Link className="studio-logo" to="/"><BrandLogo/></Link><p>Perencanaan dan kolaborasi konten untuk bisnis.</p></div><div><a href="#paket">Paket & harga</a><Link to="/login">Masuk</Link><a href="https://wa.me/6285111037992" target="_blank" rel="noopener noreferrer">Hubungi kami</a></div><small>© {new Date().getFullYear()} plannersm.co</small></footer><StudioInteractions/>
 </div>
}

